export const en = {
  appName: "AgriBridge",
  tagline: "AI-powered climate-resilient farming for a connected world",
  subTagline: "Local advice. Shared knowledge. Sustainable harvests.",
  themeBadge: "BRICS AgriN Cooperative Network",

  // Navigation
  nav: {
    overview: "Overview",
    myFarm: "My Farm",
    advisory: "AI Advisory",
    diagnosis: "Crop Diagnosis",
    regenerative: "Regenerative Farming",
    weather: "Weather & Climate",
    cooperation: "Data Cooperation",
    settings: "Settings",
    tour: "Guided Tour",
  },

  // Dashboard Overview
  overview: {
    greeting: "Good evening, Farmer",
    greetingSub: "Your farm is moderately healthy. Rainfall is expected in 3 days. Review today’s recommendations before irrigation.",
    areaLabel: "Farm Area",
    cropLabel: "Crop",
    cropAgeLabel: "Crop Age",
    healthStatusLabel: "Farm Health",
    lastUpdated: "Last updated",
    days: "days",
    acres: "acres",
    moderate: "Moderate",
    good: "Good",
    attentionNeeded: "Needs attention",

    // Key metrics
    cropHealthTitle: "Crop Health",
    cropHealthDesc: "Based on satellite vegetation indicators (NDVI) and field observations",
    soilMoistureTitle: "Soil Moisture",
    soilMoistureDesc: "Soil sensor reading at 15cm depth. Inspect field before pump start.",
    rainfallTitle: "Rainfall Forecast",
    rainfallDesc: "Next 3 days outlook. Moderate probability of convective showers.",
    diseaseRiskTitle: "Disease Risk",
    diseaseRiskDesc: "High humidity and leaf wetness favor leaf spot development.",
    viewDiagnosis: "Open Diagnosis",

    // Priority advisory
    priorityTag: "Priority action for today",
    priorityTitle: "Delay irrigation for 24 hours and inspect lower leaves",
    priorityDesc: "Rainfall probability is increasing (68% chance). Soil moisture is currently 34%, sufficient for flowering stage. Check underside of lower leaves for early brown circular spots.",
    viewFullAdvisory: "View full advisory",
    markCompleted: "Mark as completed",
    completed: "Action Completed",

    // Chart
    healthChartTitle: "Farm Health & Environmental Trends",
    chartSubtitle: "Multi-parameter telemetry tracking crop vigor, soil moisture, and heat stress",
    filter7Days: "7 Days",
    filter14Days: "14 Days",
    filter30Days: "30 Days",
    legendHealth: "Crop Health Index",
    legendMoisture: "Soil Moisture (%)",
    legendStress: "Temp Stress (°C)",

    // Weather preview
    weatherPreviewTitle: "5-Day Weather Forecast",
    bestIrrigationDay: "Best irrigation day",
    rainfallWarning: "Rainfall expected",
    heatStressWarning: "High heat stress",

    // Recent activity
    recentActivityTitle: "Recent Farm Activity",
    actSatellite: "Satellite vegetation index updated (Sentinel-2 L2A)",
    actSensor: "Soil sensor AGRI-ESP32-001 synchronized successfully",
    actAdvisory: "New localized irrigation advisory generated by AgriAI",
    actDiagnosis: "Groundnut leaf image analyzed for Cercospora spot",
    actCompleted: "Farmer marked irrigation delay action as completed",
  },

  // My Farm
  farm: {
    title: "My Farm Profile & Telemetry",
    subtitle: "Manage plot boundaries, soil profile, crop growth stages, and IoT sensors",
    detailsTitle: "Plot Details",
    farmName: "Farm Name",
    farmerName: "Farmer Name",
    location: "Location",
    area: "Total Area",
    crop: "Active Crop",
    sowingDate: "Sowing Date",
    growthStage: "Growth Stage",
    soilType: "Soil Type",
    irrigationType: "Irrigation Method",
    editFarm: "Edit Farm Details",
    saveFarm: "Save Farm Details",
    cancel: "Cancel",

    // Map
    mapTitle: "Interactive Farm Boundary",
    mapLegendField: "Farm Plot Boundary",
    mapLegendSensor: "IoT Sensor Node",
    mapCoords: "Coordinates",
    layerSatellite: "Satellite TrueColor",
    layerNdvi: "NDVI Vegetation Heatmap",
    zoomIn: "Zoom In",
    zoomOut: "Zoom Out",

    // Sensor
    sensorTitle: "Connected IoT Sensor",
    deviceId: "Device ID",
    sensorStatus: "Status",
    battery: "Battery Level",
    lastSync: "Last Sync",
    syncNow: "Sync Sensor Now",
    syncing: "Synchronizing telemetry...",
    sensorOnline: "Online & Calibrated",
    sensorMoisture: "Volumetric Soil Water",
    sensorTemp: "Soil Temperature",
    sensorHumidity: "Canopy Humidity",
  },

  // AI Advisory
  advisory: {
    title: "Localized AI Agro-Advisories",
    subtitle: "Context-aware recommendations combining satellites, soil sensors, crop models, and weather",
    categoryAll: "All Categories",
    catIrrigation: "Irrigation",
    catFertilizer: "Fertilizer & Nutrition",
    catPest: "Pest & Disease",
    catWeather: "Weather Alert",
    catSoil: "Soil Health",
    catRegenerative: "Regenerative Practice",
    catHarvest: "Harvest Planning",

    reasonLabel: "Reason for recommendation",
    actionLabel: "Recommended action",
    benefitLabel: "Expected benefit",
    sourcesLabel: "Data sources used",
    confidenceLabel: "Confidence score",
    shareOfficer: "Share with Extension Officer",
    shareToast: "Advisory summary copied for WhatsApp / Extension Officer sharing!",

    // Ask AgriAI
    chatTitle: "Ask AgriAI Assistant",
    chatSub: "Safe, explainable farming advice supported by multi-source data",
    chatPlaceholder: "Ask about irrigation, pest diagnosis, or fertilizers...",
    send: "Ask",
    suggestedTitle: "Frequently asked questions:",
    q1: "Should I irrigate today?",
    q2: "Why are my groundnut leaves turning yellow?",
    q3: "Which regenerative practice should I follow this month?",
    q4: "When should I apply organic fertilizer?",
  },

  // Crop Diagnosis
  diagnosis: {
    title: "AI Crop Disease Diagnosis",
    subtitle: "Early screening of crop foliage using computer vision and agronomic rules",
    uploadTitle: "Upload Crop Leaf Photo",
    uploadPrompt: "Drag & drop leaf photo here, or click to browse",
    uploadCamera: "Take Photo / Select File",
    uploadFormats: "Supported formats: JPG, PNG, WEBP (Max 10MB)",
    useSampleBtn: "Use sample leaf image",
    analyzeBtn: "Analyze Leaf with AgriAI",
    analyzingText: "Analyzing leaf image with AgriAI neural model...",
    removeBtn: "Remove image",

    // Result
    resultTitle: "Diagnostic Assessment",
    conditionLabel: "Probable Condition",
    confidenceLabel: "Confidence",
    severityLabel: "Severity Level",
    affectedLabel: "Affected Canopy Area",
    symptomsTitle: "Symptoms Detected",
    immediateActionTitle: "Immediate Recommended Action",
    preventionTitle: "Cultural & Preventive Practices",
    expertConsultTitle: "When to Consult Extension Officer",
    expertConsultDesc: "If spots cover more than 20% of the upper canopy or if defoliation occurs, immediately contact the Kurnool Krishi Vigyan Kendra (KVK).",
    disclaimer: "AI diagnosis is an early screening decision-support tool. Confirm serious cases with an agricultural officer before applying chemical treatments.",

    historyTitle: "Recent Diagnostic Scans",
    scanDate: "Scan Date",
    scanCrop: "Crop",
    scanDiagnosis: "Diagnosis",
    scanConfidence: "Confidence",
    scanStatus: "Action Status",
  },

  // Regenerative Farming
  regen: {
    title: "Regenerative & Climate-Resilient Practices",
    subtitle: "Restore soil biology, conserve water, and reduce expensive chemical inputs",
    scoreTitle: "Your Regenerative Score",
    targetScoreLabel: "Target Score",
    scoreExplain: "Calculated across 5 core pillars: soil cover, organic matter, crop diversity, water stewardship, and biological protection.",
    p1: "Soil Cover & Mulching",
    p2: "Crop Diversity & Rotation",
    p3: "Water Efficiency & Micro-irrigation",
    p4: "Organic Matter & Compost",
    p5: "Integrated Biological Pest Management",

    addToPlan: "Add practice to my farm plan",
    inPlan: "Active in farm plan",
    removeFromPlan: "Remove from plan",
    addedToast: "Practice added to farm plan! Regenerative score updated.",
    removedToast: "Practice removed from farm plan.",
  },

  // Weather
  weather: {
    title: "Weather & Climate Intelligence",
    subtitle: "Hyper-local 7-day meteorological forecasts and climate resilience alerts",
    currentConditions: "Current Conditions in Kurnool",
    temp: "Temperature",
    feelsLike: "Feels Like",
    humidity: "Humidity",
    windSpeed: "Wind Speed",
    barometer: "Pressure",
    uvIndex: "UV Index",
    droughtRisk: "Dry-Spell Risk",
    heatRisk: "Heat Stress",

    climateAlertTitle: "Climate Risk Notice: Moderate dry-spell risk in 10-day window",
    climateAlertDesc: "Soil evaporation is expected to increase next week. Preserve straw mulch, monitor tensiometer, and schedule irrigation during early morning hours.",
    chartRainTemp: "7-Day Rainfall & Temperature Outlook",
  },

  // BRICS Data Cooperation
  brics: {
    title: "BRICS Agricultural Data Cooperation",
    tagline: "Interoperable digital public goods for global food security",
    intro: "AgriBridge uses shared standards and country-specific data adapters so agricultural institutions can cooperate without forcing all data into one central database.",
    networkTitle: "BRICS AgriN Collaborative Topology",
    networkDesc: "Real-time distributed data mesh connecting agricultural research institutes, meteorological agencies, and farmer cooperatives.",
    legendActive: "Connected Hub",
    legendPartner: "Research Partner",

    statusTitle: "Interoperability Protocol Status",
    schemaStatus: "Common Agricultural Data Schema (CADS)",
    gatewayStatus: "Decentralized API Gateway",
    registryStatus: "Federated Agro-AI Model Registry",
    transStatus: "Multilingual Agricultural Translation Layer",
    privacyStatus: "Differential Privacy & PII Stripping",
    provenanceStatus: "Verifiable Data Provenance Ledger",
    activeStatus: "Active",

    simulatorTitle: "Simulate Cross-Border Data Exchange",
    simulatorDesc: "Test interoperability by transmitting standardized agronomic indicators between BRICS national adapters without exposing farmer personal data.",
    sourceLabel: "Source Country",
    dataTypeLabel: "Data Indicator Type",
    destLabel: "Destination Partner",
    simulateBtn: "Simulate Data Exchange",
    simulatingBtn: "Routing through AgriBridge Gateway...",
    exchangeSuccess: "Interoperable data exchange simulated successfully!",
    schemaNote: "AgriBridge prototype interoperability schema (anonymized data payload):",
  },

  // Settings
  settings: {
    title: "Application & System Settings",
    subtitle: "Manage language, unit preferences, low-bandwidth mode, offline cache, and data privacy",
    prefTitle: "Preferences",
    language: "Display Language",
    units: "Measurement Units",
    metricUnits: "Metric (Hectares, °C, mm)",
    imperialUnits: "Indian Traditional (Acres, °C, mm)",

    networkTitle: "Network & Bandwidth Optimization",
    lowBandwidthMode: "Low-Bandwidth Mode",
    lowBandwidthDesc: "Disables animations, suppresses heavy imagery, and reduces data usage for 2G/3G mobile networks.",
    offlineCache: "Offline Advisory Cache",
    offlineDesc: "Store the latest farm advisories, sensor readings, and weather offline on your phone.",
    clearCacheBtn: "Clear Local Cache",
    cacheClearedToast: "Local offline cache cleared.",

    privacyTitle: "Data Privacy & BRICS Sharing Consent",
    privacyNotice: "Your farm data remains under your control. Sharing is optional and uses anonymized or aggregated information.",
    consentBrics: "Contribute anonymized soil moisture & crop health to BRICS research mesh",
    consentSatellite: "Allow ground-truth calibration for satellite vegetation models",

    resetTitle: "Demo Controls",
    resetBtn: "Reset Demo Data to Default",
    resetToast: "Demo data has been restored to default state.",
  },

  // Common buttons & notifications
  common: {
    demoBadge: "Demo Mode Active",
    resetDemo: "Reset Demo",
    loading: "Loading...",
    save: "Save",
    close: "Close",
    success: "Success",
    error: "Error",
    online: "Online",
    offline: "Offline Mode",
  }
};
